variable "name" {}
variable "protocol" {}
variable "port_name" {}
variable "load_balancing_scheme" {}
variable "timeout_sec" {}
variable "enable_cdn" {}
variable "custom_request_headers" {}
variable "custom_response_headers" {}
variable "health_checks" {}
variable "backends" {}